### ISSUE TITLE
OpenAI voices do not work if a custom GPT Prompt is active

### ISSUE THREAD

**Issue by Zomboy4313** [kercre123/WirePod#21]
I've been trying to figure out why the OpenAI TTS voice for English wasn't working, and I found out that WirePod errors when a GPT Prompt is active. The attached image shows that WirePod does not send a correct name for the voice, and thus Vector will be silent.![image](https://github.com/user-attachments/assets/cd05facb-8052-4eea-9159-129f3f7735ec)

**Comment by mr-kristoffer** [comment]
I can confirm that I am having the same issue.  Also it appear the OpenAI TTS Voice selection is not being respected as well. No matter what voice I select, the voice always seems to sound like Fable.

**Comment by Zomboy4313** [comment]
This seems to be fixed in the latest update
