### ISSUE TITLE
BLE doesn't seem to work on Windows install

### ISSUE THREAD

**Issue by Zomboy4313** [kercre123/WirePod#22]
Whilst reinstalling WirePod I noticed in the logs that the BLE API does not get set up correctly, I think this is what causes the WirePod Web Interface to not allow directly allow Bot Setup. But I can confirm that my device supports BLE and I used the alternative method on the same device and that worked fine
<img width="1074" alt="Screenshot 2024-08-21 at 23 19 42" src="https://github.com/user-attachments/assets/1678e908-77be-47ef-9758-908b1d66ac65">
<img width="820" alt="Screenshot 2024-08-21 at 23 03 31" src="https://github.com/user-attachments/assets/dec90feb-7c83-49c5-a20f-213f663fb562">
.

**Comment by kercre123** [comment]
Inbuilt BLE only works on Linux systems at the moment, and is only built in to the wire-pod binary if the build flag "inbuiltble" is added. It is only built in to the .deb releases.

**Comment by Zomboy4313** [comment]
Ah ok, that explains why it used to work on my Raspberry Pi. Sorry about another random issue 😅
