### ISSUE TITLE
Works Fine on Android 13 (API LEVEL 33)

### ISSUE THREAD

**Issue by F4310** [kercre123/WirePod#3]
Works Fine on Android 13 (API LEVEL 33)
I just can't access using escapepod.local
After some time, the server stops and need to be started again.

**Comment by F4310** [comment]
After some time, when the **screen is locked**, the server stops.

**Comment by kercre123** [comment]
It only becomes accessible on escapepod.local when a bot has connected to the network. This just makes setup more seamless as it makes sure the bot sees the broadcast before the "ACTIVATE" button is pressed.

The device must be plugged in for the server to stay on. I don't think I can get past Android's battery management.
